version: "3"
services:
  package:
    image: registry.gitlab.com/aplus-framework/images/package:4
    container_name: package-debug
    working_dir: /package
    volumes:
      - .:/package
    tty: true
  package-latest:
    image: registry.gitlab.com/aplus-framework/images/package:latest
    container_name: package-debug-latest
    working_dir: /package
    volumes:
      - .:/package
    tty: true
